kind: pipeline
name: default

steps:
- name: install
  image: composer
  commands:
  - composer install --ignore-platform-reqs --no-scripts

- name: test
  image: php:7
  commands:
    - ./vendor/bin/phplint ./ --exclude=vendor
