kind: pipeline
name: default

steps:
- name: install
  image: composer
  commands:
  - pecl install mongodb
  - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install

- name: test
  image: php:7
  commands:
    - ./vendor/bin/phplint ./ --exclude=vendor
